services:
  spiga_backend_stage:
    image: spiga-backend-stage
    build:
      context: .
      dockerfile: Dockerfile.stage
    ports:
      - "8082:8082"
    depends_on:
      - spiga_postgres_stage
    profiles:
      - stage

  spiga_postgres_stage:
    container_name: spiga-postgres-stage
    image: postgres:latest
    environment:
      POSTGRES_DB: ${STAGE_DB_NAME}
      POSTGRES_USER: ${STAGE_DB_USERNAME}
      POSTGRES_PASSWORD: ${STAGE_DB_PASSWORD}
    ports:
      - "5434:5432"
    volumes:
      - postgres_development_data:/var/lib/postgresql/data
    profiles:
      - stage
    env_file:
      - .env

volumes:
  postgres_development_data: {}
