services:
  spiga_backend_prod:
    image: spiga-backend-prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "8083:8083"
    depends_on:
      - spiga_postgres_prod
    profiles:
      - production

  spiga_postgres_prod:
    container_name: spiga-postgres-prod
    image: postgres:latest
    environment:
      POSTGRES_DB: ${PROD_DB_NAME}
      POSTGRES_USER: ${PROD_DB_USERNAME}
      POSTGRES_PASSWORD: ${PROD_DB_PASSWORD}
    ports:
      - "5435:5432"
    volumes:
      - postgres_development_data:/var/lib/postgresql/data
    profiles:
      - production
    env_file:
      - .env

volumes:
  postgres_development_data: {}
