server:
  port: '8082'

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: '${STAGE_DB_URL}'
    username: '${STAGE_DB_USERNAME}'
    password: '${STAGE_DB_PASSWORD}'
    hikari:
      connection-timeout: 25000
      maximum-pool-size: 10
      minimum-idle: 8
      idle-timeout: 50000
      validation-timeout: 3000
      max-lifetime: 15000

  jpa:
    show-sql: false

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        boot:
          allow_jdbc_medata_access: false

    hibernate:
      ddl-auto: validate

  sql:
    init:
      mode:
        never
