server:
  port: '8083'

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: '${PROD_DB_URL}'
    username: '${PROD_DB_USERNAME}'
    password: '${PROD_DB_PASSWORD}'
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 20
      minimum-idle: 10
      idle-timeout: 60000
      validation-timeout: 5000
      max-lifetime: 18000

  jpa:
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        boot:
          allow_jdbc_metadata_access: false

  sql:
    init:
      mode: never
